#List 
List adalah struktur data pada python yang mampu menyimpan lebih dari satu data, seperti array. List bersifat mutable, artinya bisa diubah-ubah. 
Check this out : https://towardsdatascience.com/python-basics-6-lists-and-list-manipulation-a56be62b1f95

In [ ]:
#Contoh List 1
group_A = ['England','Portugal','Belgium']
group_B = ['France', 'Holland', 'Spain']



print(group_A)
print(group_B)

['England', 'Portugal', 'Belgium']
['France', 'Holland', 'Spain']




#Latihan 1
List diatas merupakan contoh negara yang tergabung dalam Euro Cup Qualifier, pada tiap Group seharusnya ada 5 negara. Namun pada list diatas masih ada 3 negara. Silahkan tambahkan 2 negara di eropa (bebas) ke dalam masing-masing Group A dan Group B, boleh dengan extend maupun insert. Jangan lupa tampilkan list kedua Group tersebut.

In [3]:
#Latihan 1 Kerjakan Disini
#Contoh List 1
group_A = ['England','Portugal','Belgium']
group_B = ['France', 'Holland', 'Spain']

group_A.extend(['Italia' ,'Rusia'])
group_B.insert(0,('Brazil' ,'Belanda'))

print(group_A)
print(group_B)

['England', 'Portugal', 'Belgium', 'Italia', 'Rusia']
[('Brazil', 'Belanda'), 'France', 'Holland', 'Spain']

In [4]:
#Contoh List 2
hari = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat']
subject = ['Networking','BigData','Cybersecurity','DigitalForensics','EthicalHacking']

Senin Networking

#Latihan 2
List diatas merupakan subjek mata kuliah kalian di semester ini. Lengkapi source code diatas untuk mengeluarkan input hari ini dan mata kuliah yang sedang kalian ikuti saat ini. Contoh output : Senin DigitalForensics

In [5]:
#Latihan 2 Kerjakan Disini
hari = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat']
subject = ['Networking','BigData','Cybersecurity','DigitalForensics','EthicalHacking']
print(hari[1], subject[1])

Selasa BigData

#Tuple
Tuple dalam Python adalah stuktur data yang digunakan untuk menyimpan sekumpulan data. Bersifat immutable, artinya isi tuple tidak bisa kita ubah dan hapus. Namun, dapat diisi dengan berbagai macam nilai dan objek. 

Source : https://www.w3schools.com/python/python_tuples.asp

In [ ]:
#Contoh Tuple 1
Bulan = ('Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember')
print("Jumlah bulan di satu tahun: %d" % len(Bulan))

Jumlah bulan di satu tahun: 12

#Latihan 3
Buatlah tuple barang bawaan kalian ketika ke kampus untuk mengikuti perkuliahan offline terbatas. Lalu berikan keterangan berapa jumlah total barang yang kalian bawa, seperti Contoh Tuple 1 diatas!

In [6]:
#Latihan 3 Kerjakan Disini
Barang = ('Leptop','Hp','Buku','Pulpen')
print("Jumlah barang yang di bawa : %d" % len(Barang))

Jumlah barang yang di bawa : 4

#Set
Set adalah tipe data kolektif yang digunakan untuk menyimpan banyak nilai dalam satu variabel. Dengan beberapa detail khusus yaitu tidak ada duplikasi, bersifat unordered, nilai yang sudah dimasukkan bersifat unchangeable.

Source : https://www.w3schools.com/python/python_sets.asp , https://www.malasngoding.com/operasi-tipe-data-set/

In [ ]:
#Contoh Set 1
Contoh_Dosen_Idaman = {'Pak Anggit', 'Bu Senie', 'Pak Wahid', 'Bu Rina', 'Pak Jeki', 'Bu Rini'}
print(Contoh_Dosen_Idaman)

{'Bu Senie', 'Pak Wahid', 'Bu Rina', 'Pak Anggit', 'Bu Rini', 'Pak Jeki'}

Tipe data kolektif ini sangat unik, python menyediakan kepada kita berbagai fungsi keanggotaan yang berguna untuk pengolahan data. 
Di antaranya : fungsi union (gabungan), serta fungsi intersection (irisan).

In [7]:
#Contoh Set 2
ChelseaFC = {'Kai Havertz', 'Hakim Ziyech', 'Mason Mount', 'Ben Chilwell','Romelu Lukaku','Reece James','Thiago Silva'}
England = {'Harry Kane','Mason Mount','Jadon Sancho','Ben Chilwell','Reece James','Phil Foden','Dean Henderson'}

print(England)

{'Kai Havertz', 'Ben Chilwell', 'Thiago Silva', 'Reece James', 'Romelu Lukaku', 'Hakim Ziyech', 'Mason Mount'}

#Latihan 4
Lengkapi source code pada Set 2 diatas dengan fungsi union dan intersection!

In [12]:
#Latihan 4 Kerjakan Disini
ChelseaFC = {'Kai Havertz', 'Hakim Ziyech', 'Mason Mount', 'Ben Chilwell','Romelu Lukaku','Reece James','Thiago Silva'}
England = {'Harry Kane','Mason Mount','Jadon Sancho','Ben Chilwell','Reece James','Phil Foden','Dean Henderson'}

#Union
print(ChelseaFC|England)


#Intersection
print(ChelseaFC & England)

{'Kai Havertz', 'Ben Chilwell', 'Thiago Silva', 'Jadon Sancho', 'Phil Foden', 'Reece James', 'Romelu Lukaku', 'Harry Kane', 'Dean Henderson', 'Hakim Ziyech', 'Mason Mount'}
{'Mason Mount', 'Ben Chilwell', 'Reece James'}

#Dictionary
Dictionary adalah tipe data pada python yang berfungsi untuk menyimpan kumpulan data/nilai dengan pendekatan “key-value”. As of Python version 3.7, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

Source : https://www.w3schools.com/python/python_dictionaries.asp

In [ ]:
#Contoh Dictionary 1
product1 = {
  "brand": "Kingston",
  "model": "USB Flash Drive V22",
  "size": "256 GB",
  "year": 2022
}
print(product1["brand"])

Kingston

In [ ]:
#Contoh Dictionary 2
Biodata = {
  'nama': 'Robert Langdon',
  'usia': 23,
  'asal': 'Sleman'
}
print(Biodata['usia'])

23

#Latihan 5
Ubahlah data pada contoh dictionary 1 atau 2 (pilih salah satu). Data yang diubah bebas, dan pastikan tampilkan output yang sesuai!

In [18]:
#Kerjakan Latihan 5 disini
#Contoh Dictionary 2
Biodata = {
  'nama': 'Excel',
  'usia': 21,
  'asal': 'Sleman'
}
print(Biodata['nama'])
print(Biodata["usia"])

Excel
21

#String Processing
String adalah jenis yang paling populer di bahasa pemrograman. Kita bisa membuatnya hanya dengan melampirkan karakter dalam tanda kutip. Python memperlakukan tanda kutip tunggal sama dengan tanda kutip ganda. Membuat string semudah memberi nilai pada sebuah variabel.

Source : https://jagongoding.com/python/menengah/manipulasi-string-part-1/

In [28]:
#Contoh String Concatenation
kata1 = 'Universitas'
kata2 = ' Amikom'
kata3 = ' Yogyakarta'
kalimat=kata1 + kata2 + kata3

print(kalimat)

Universitas Amikom Yogyakarta

In [ ]:
#Contoh String Slicing
Z = 'Rara Mandalika'
X = 'is a Cloud Engineer'

print ("Z[5]:", Z[5])
print ("X[5:10]:", X[5:10])

Z[5]: M
X[5:10]: Cloud

In [ ]:
#Contoh String Conversion
kata1 = '18830177'
kata1= int (kata1)+666

print (kata1)

18830843

In [ ]:
#Contoh String Read
nama=input('Nama Anda : ')
usia=input('Usia Anda Tahun Lalu: ')
usia= int(usia) + 1

print ("Name: %s"% nama ,"\t Usia Saat Ini:%d"% usia)

Nama Anda : Dika
Usia Anda Tahun Lalu: 22
Name: Dika 	 Usia Saat Ini:23

#Latihan 6
Lengkapi source code dibawah agar tidak menjadi error. Dan perhatikan outputnya!

In [38]:
k1 =' Prodi Teknik Komputer'
k2 =' Universitas Amikom Yogyakarta!'
k3 ='Para Mahasiswa baru, selamat datang di'
k  = k3 + k1 + k2


print (k2.lower())
print (k.upper())
print (len(k))

 universitas amikom yogyakarta!
PARA MAHASISWA BARU, SELAMAT DATANG DI PRODI TEKNIK KOMPUTER UNIVERSITAS AMIKOM YOGYAKARTA!
91