# **NumPy**
NumPy merupakan singkatan dari **Numerical Python**, NumPy menjadi salah satu library yang sangat penting karena hampir semua packages yang digunakan untuk data science maupun machine learning pada Python, seperti SciPy, MatPlotlib, Scikit-learn, dan lain sebagainya sering kali dikombinasikan dengan library NumPy. Salah satu fungsi NumPy adalah untuk melakukan operasi matematika dan logika pada Array. Library ini menyediakan banyak fitur yang berguna pada operasi pada n-array dan matriks pada bahasa pemrograman Python. NumPy merupakan library powerful untuk komputasi numerik yang cepat dan akurat untuk mengolah big data.

## Instalasi NumPy 
Sebelum Menggunakan NumPy, pastikan bahwa NumPy telah terinstall pada environment yang digunakan.
untuk menginstall NumPy, gunakan perintah berikut:

In [1]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.21.5)

## Menggunakan NumPy
untuk menggunakan NumPy, perlu dilakukan proses import pada lembar kerja yang akan digunakan. 

perintah yang digunakan untuk import numpy adalah sebagai berikut:

In [2]:
import numpy as np

## Cek Versi NumPy
untuk memastikan NumPy berjalan dengan baik. langkah awal yang perlu dilakukan adalah melakukan check versi dari numpy yang digunakan. 

perintah untuk menampilkan versi dari numpy adalah sebagai berikut:

In [3]:
np.__version__

'1.21.5'

**np** adalah alias dari library numpy yang diimport pada lembar kerja, sedangkan **version** adalah perintah untuk memunculkan versi dari NumPy yang digunakan.

## Built in Documentation NumPy
untuk menampilkan built-in documentation NumPy, gunakan perintah berikut:

In [4]:
np?

# **Dasar-dasar NumPy Arrays**

## Membuat Array dari List
untuk membuat array, gunakan perintah ``np.array`` diikuti dengan list yang akan dibuat dalam bentuk array

In [42]:
#list python
L = [1,2,3,4]

#cetak List
print('list terbentuk: ', L*2, 'tipe datanya:', type(L))

#array dari list
arr = np.array(L)

#cetak tipe datanya
print('array data:', arr*2, 'tipe datanya:', type(arr))

list terbentuk:  [1, 2, 3, 4, 1, 2, 3, 4] tipe datanya: <class 'list'>
array data: [2 4 6 8] tipe datanya: <class 'numpy.ndarray'>

**WARNING !!!** <br>
meskipun memiliki bentuk yang sama, namun Array memiliki perbedaan dengan List pada Python, yaitu, data pada Array harus memiliki tipe data yang sama. apabila ada tipe data yang berbeda, maka data tersebut akan di casting ke tipe data yang memungkinkan. <br>

perhatikan contoh berikut ini:

In [6]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

pada contoh tersebut, terlihat adanya nilai ``3.14`` yang bertipe ``float`` berbeda dengan tipe data pada nilai lainnya, akan tetapi, apabila dibuat dalam bentuk Array, maka secara keseluruhan data pada array tersebut akan disamakan tipedatanya menjadi float yang membuat nilai ``4``, ``2``, dan ``3`` memiliki floating point menjadi ``4.0``, ``2.0``, dan ``3.0``.

daftar lengkap tipe data yang dapat digunakan: <br>

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats|

akan tetapi, jika kita ingin mengatur tipe data dari array yang dihasilkan secara eksplisit, kita dapat menggunakan kata kunci ``dtype``. 
sebagai contoh:

In [7]:
np.array([1, 2, 3, 4], dtype='float32') #float32 adalah tipe data float

array([1., 2., 3., 4.], dtype=float32)

``float32`` adalah tipe data yang diberikan secara eksplisit, agar semua item pada array memiliki tipe data float. oleh karena itu, pada contoh tersebut semua nilai (item) pada Array memiliki *floating point*, meskipun inisialisasi awal data adalah nilai *integer*.

## Multi Dimensional Array

In [10]:
#membuat Array 2 Dimensi
array2D = np.array([ [2, 3, 4], 
                    [5, 6, 7] 
                    ])
array2D

array([[2, 3, 4],
       [5, 6, 7]])

In [11]:
#membuat Array 3 Dimensi
array3D = np.array([
                    [
                     [1,2], 
                     [4,5]
                     ], [
                         [7,8], 
                         [9,0]
                         ]
                    ])

array3D

array([[[1, 2],
        [4, 5]],

       [[7, 8],
        [9, 0]]])

## Built-in Array
Khusus untuk array dengan dimensi yang lebih besar, akan lebih efisien untuk membuat array dari awal menggunakan *sub-routine* yang dibangun ke dalam NumPy. <br>
Berikut adalah beberapa contoh:

In [12]:
# membuat array sebanyak 10 elemen dengan masing-masing elemen tersebut bernilai nol (0)
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# membuat array dengan ukuran 3x5 yang masing-masing elemennya memiliki nilai satu (1) dengan tipe float. 
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# membuat array dengan ukuran 3x5 yang setiap elemennya bernilai 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Membuat array dengan jumlah elemen beserta nilai tertentu.
# Ex : array yang berisi rentang interval yang berjarak sama, 
#format: arange(nilai minimal, nilai maksimal, interval)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#membuat array pada interval tertentu dengan jumlah tertentu secara linear. 
# sebagai contoh: membuat array dengan nilai antara 0 hingga 1 sebanyak 5 elemen
#format: linspace(nilai minimal, nilai maksimal, interval)

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# membuat array dengan ukuran 3x3 yang berisi elemen dengan nilai antara 0-10 
np.random.randint(0, 10, (3, 3))

array([[7, 0, 5],
       [8, 6, 9],
       [5, 5, 2]])

In [18]:
# membuat matriks identitas dengan ukuran 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# membuat array random untuk multidimensi 
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print('1D random array')
print(x1)
print()
print('2D random array')
print(x2)
print()
print('3D random array')
print(x3)

1D random array
[5 0 3 3 7 9]

2D random array
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

3D random array
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

## NumPy Attribute

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

Setiap Array memiliki atribut ``ndim`` (jumlah dimensi), ``shape`` (ukuran untuk setiap dimensi), dan ``size`` (total item pada array)

In [20]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60

## Penggabungan Array

In [21]:
# Apabila anda memiliki array seperti berikut ini

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])


# Anda dapat menggabungkan array tersebut menggunakan fungsi np.concatenate().

arr = np.concatenate([x, y])

print(arr)

[1 2 3 3 2 1]

In [22]:
array2D = np.array([[1, 2, 3],
                 [4, 5, 6]])

#concatenate secara vertikal (axis = 0) #default
np.concatenate([array2D, array2D])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
#concatenate secara horizontal axis = 1
np.concatenate([array2D, array2D], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [24]:
# untuk menggabungkan dengan cara menumpuk secara vertikal, gunakan fungsi np.vstack()
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [25]:
# untuk menggabungkan dengan cara menumpuk secara horizontal, gunakan fungsi np.hstack()
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## Array Sorting

In [26]:
# Sorting ascending angka pada array 
# Apabila anda memiliki array seperti berikut ini

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
arr = np.concatenate([x, y])

#sebelum sorting
print('sebelum sorting: ', arr)

print()

#setelah sorting
print('setelah sorting', np.sort(arr))

sebelum sorting:  [1 2 3 3 2 1]

setelah sorting [1 1 2 2 3 3]

In [27]:
# Sorting descending angka pada array 

-np.sort(-arr)

array([3, 3, 2, 2, 1, 1])

## Indexing dan Slicing

In [28]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [29]:
data[0] #menampilkan data index ke 0

1

In [30]:
data[0:2] #menampilkan data pada index ke 0 hingga batasnya adalah index ke 2, index batas tidak diambil nilainya.

array([1, 2])

In [31]:
data[1:] #menampilkan data dari index ke 1 hingga index terakhir

array([2, 3, 4, 5])

In [32]:
data[-2:] #menampilkan data yang dimulai dari index ke-2 terakhir sampai dengan data pada index terakhir

array([4, 5])

## Broadcasting
Ada kalanya Anda mungkin ingin melakukan operasi antara sebuah array dengan satu angka (juga disebut operasi antara vektor dan skalar) atau antar array dengan dua ukuran berbeda. Misalnya, Array yang telah anda buat (Kita akan menyebutnya "data") mungkin berisi informasi tentang jarak dalam satuan mil tetapi anda ingin mengubah informasi tersebut dalam satuan kilometer. Anda dapat melakukan ini dengan perintah ini.

In [33]:
data = np.array ([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

## Aggregation Array
Pada bagian ini akan dibahas mengenai nilai maximum, minimum, sum, mean, product, standart deviation, dan lainnya.

NumPy juga dapat melakukan fungsi agregasi. Selain `min`, `max`, dan `sum`, Anda dapat dengan mudah menjalankan `mean` untuk mendapatkan rata-rata, `prod` untuk mendapatkan hasil perkalian elemen bersama, `std` untuk mendapatkan standar deviasi, dan lainnya.

In [34]:
dataku = np.array ([1,2,3,4])

dataku.max()

4

In [35]:
dataku.min()

1

In [36]:
dataku.sum()

10

In [37]:
dataku.mean()

2.5

In [38]:
dataku.prod()

24

In [39]:
dataku.std()

1.118033988749895

# Menampilkan Elemen Unik dan Menghitung Jumlah Elemen

Anda dapat menemukan elemen unik dalam array dengan mudah dengan `np.unique`

In [40]:
data_a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

# Anda dapat menggunakan perintah np.unique untuk menampilkan elemen yang unik.

unique_values = np.unique(data_a)
print (unique_values)

[11 12 13 14 15 16 17 18 19 20]

Untuk mendapatkan indeks nilai unik dalam array NumPy (array posisi indeks pertama dari nilai unik dalam array), cukup berikan argumen `return_index` pada `np.unique()`

In [ ]:
unique_values, indices_list = np.unique(data_a, return_index=True)
print (indices_list)

# Anda juga dapat menghitung frekuensi dari nilai unik tersebut dengan perintah berikut
unique_values, occurrence_count = np.unique(data_a, return_counts=True)
print (occurrence_count)

[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]

In [ ]:
# Hal ini juga berlaku/bekerja pada array 2d. Sebagai contoh array berikut ini

data_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[4, 3, 1, 2],[1, 2, 3, 4]])
print (data_2d)

print()
# Anda dapat mencari nilai unik pada array 2d tersebut dengan perintah berikut
unique_values = np.unique(data_2d)
print (unique_values)

print()
# Anda juga dapat menghitung frekuensi dari nilai unik tersebut
occurrence_count = np.unique(data_2d, return_counts=True)
print (occurrence_count)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 1 2]
 [1 2 3 4]]

[1 2 3 4 5 6 7 8]

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([3, 3, 3, 3, 1, 1, 1, 1]))