# **PANDAS**
Pandas (**Python Data Analysis Library**) merupakan sebuah library *open source* yang dituliskan dalam bahasa pemrograman python yang menyediakan berbagai fungsi untuk kebutuhan analisa data seperti:
. <br>

*   Load Data
*   Manipulasi Data
*   Persiapan 
*   Pemodelan data
*   Analisa data


Pandas dibangun diatas library **NumPy**, artinya banyak fungsi dan struktur dari Numpy digunakan dan direplikasi oleh Pandas. <br>
Pandas banyak digunakan dalam proses analisa data karena memiliki kinerja proses yang lebih cepat, menyediakan fungsi yang sederhana, serta lebih ekspressif dibandingkan dengan berbagai tools lainnya.

## **Instalasi Pandas**
Pandas adalah 3rd party module yang harus diinstalasi terlebih dahulu pada environment yang akan digunakan. hal tersebut perlu dilakukan karena pandas bukanlah module standar yang tersedia pada saat install python pertama kali. <br>

untuk instalasi pandas, perintah yang dilakukan adalah sebagai berikut:

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

## **Menggunakan Pandas**
Bila proses instalasi Pandas telah berhasil dilakukan pada environment yang digunakan. maka, untuk menggunakan Pandas, hal yang perlu dilakukan adalah melakukan proses import module pandas pada project yang akan dibuat. <br>
perintah untuk import pandas adalah sebagai berikut:

In [2]:
import pandas as pd
import numpy as np  
#library numpy diperlukan karena beberapa fungsi pada pandas
#terkadang memerlukan dukungan dari library numpy

## **Pandas Data Structure**
dalam pemrosesannya, pandas menggunakan 2 bentuk struktur data, yakni:

1.   [Series](#scrollto=O_COHKLH3ALY)
2.   [Data Frame](#scrollTo=c3CymV_1RXxK)

### **Series**
Series didefinisikan sebagai *One-Dimensional Array* (Array Dimensi 1) yang dapat menyimpan berbagai tipe data. sama seperti Array pada Numpy, Series menggunakan index untuk memberikan identitas pada setiap datanya. <br>
Series dapat dibentuk dengan mudah menggunakan method "Series" menggunakan data dalam bentuk array, dictionary, dan scalar value

#### Pembuatan Series
Pembuatan Series pada library pandas dilakukan menggunakan method `Series()`

##### Pembuatan Series dengan Array

In [7]:
#definisi array dengan fungsi array pada numpy
data = np.array([1, 2, 3, 4, 5])

#membuat series pada dari item yang ada pada variabel data
dt_series = pd.Series(data)

#menampilkan data series
print(dt_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

##### Pembuatan series dengan Dictionary

In [11]:
# definisi data dalam bentuk dictionary
dt_dictio = {
    'Aldo': 3,
    'Rama' : 5,
    'Mina' : 2, 
    'Bram' : 1,
    'Hilda' : 3
}

#membuat series pada dari item yang ada pada variabel dt_dictio
dt_series = pd.Series(dt_dictio)

#menampilkan data series
print(dt_series)

Aldo     3
Rama     5
Mina     2
Bram     1
Hilda    3
dtype: int64

##### Pembuatan series dari Scalar value
Scalar Value, berarti nilai tunggal. <br>
Sehingga perlu diperhatikan adalah, ketika membuat series dari scalar value perlu memberikan **parameter** ***index***  sebagai bentuk pengulangan dari banyaknya nilai scalar yang akan dibentuk sebagai series.

In [14]:
#membuat series dari scalar value
scal_value = 100
dt_series = pd.Series(scal_value, index=['a', 'b', 'c', 'd', 'e'])

#menampilkan data series
print(dt_series)

a    100
b    100
c    100
d    100
e    100
dtype: int64

#### Akses data dari Series

In [21]:
# pembuatan data series
nilai = pd.Series([100, 83, 90, 78, 65], index=['Anya', 'Marcell', 'Dea', 'Riski', 'Lydia'])

#menampilkan semua nilai
print('akses seluruh series')
print(nilai)
print()

#menampilkan menggunakan index ke-
print('akses series menggunakan index ke-')
print('nilai :', nilai[1])
print()

#menampilkan menggunakan nama indexnya 
print('akses series menggunakan nama indexnya')
print('nilai :', nilai['Riski'])

akses seluruh series
Anya       100
Marcell     83
Dea         90
Riski       78
Lydia       65
dtype: int64

akses series menggunakan index ke-
nilai : 83

akses series menggunakan nama indexnya
nilai : 78

#### Function Popular pada Series Data
berikut ini fungsi-fungsi populer yang digunakan pada analisa data Series

##### Series.map()
map() merupakan fungsi yang digunakan untuk mensubstitusi setiap nilai dalam suatu Series dengan nilai lain, yang dapat diturunkan dari suatu fungsi, dictionary, atau Series.

In [ ]:
# pembuatan series 
s = pd.Series(['kucing', 'anjing', np.nan, 'kelinci']) 
print(s)

0     kucing
1     anjing
2        NaN
3    kelinci
dtype: object

In [ ]:
#penggunaan map
s.map('{} adalah hewan favorit saya'.format)

0     kucing adalah hewan favorit saya
1     anjing adalah hewan favorit saya
2        nan adalah hewan favorit saya
3    kelinci adalah hewan favorit saya
dtype: object

In [ ]:
#untuk mencegah pemetaan pada data yang missing (np.nan), tambahkan na_action='ignore'
s.map('{} adalah hewan favorit saya'.format, na_action='ignore')

0     kucing adalah hewan favorit saya
1     anjing adalah hewan favorit saya
2                                  NaN
3    kelinci adalah hewan favorit saya
dtype: object

##### Series.value_counts()
merupakan sebuah fungsi yang mengembalikan nilai dalam bentuk series yang berisi jumlah nilai unique. <br>

In [26]:
# basic penggunaan
s = pd.Series([3, 1, 3, np.nan, 3, 4, np.nan])
s.value_counts()

3.0    3
1.0    1
4.0    1
dtype: int64

In [ ]:
# agar missing values juga terhitung
# set dropna=False
s.value_counts(dropna=False)

3.0    3
NaN    2
1.0    1
4.0    1
dtype: int64

##### Series.sort_values()
merupakan fungsi yang berperan untuk mengurutkan Series secara Ascending (A-Z) maupun Descending (Z-A) yang didasarkan pada beberapa kriteria

In [30]:
#pembuatan series
s = pd.Series([3, 1, 3, np.nan, 3, 4, np.nan])
print(s)

0    3.0
1    1.0
2    3.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [28]:
#sorting series secara ascending (A-Z)
s.sort_values(ascending=True)

1    1.0
0    3.0
2    3.0
4    3.0
5    4.0
3    NaN
6    NaN
dtype: float64

In [ ]:
#sorting dengan posisi missing values diawal
s.sort_values(na_position='first')

3    NaN
6    NaN
1    1.0
0    3.0
2    3.0
4    3.0
5    4.0
dtype: float64

In [ ]:
#sorting series secara descending (Z-A)
s.sort_values(ascending=False)

5    4.0
0    3.0
2    3.0
4    3.0
1    1.0
3    NaN
6    NaN
dtype: float64

### **Data Frame**
Data frame merupakan array dua dimensi yang memiliki baris dan kolom. Data frame merupakan cara paling umum yang digunakan untuk menyimpan data yang akan dianalisis. Secara sederhana, data frame merupakan tabel data / data tabular, dimana setiap kolomnya merupakan Series, dan setiap barisnya terdiri dari nilai yang ada pada Series. <br>

berikut ilustrasi dari series dan data frame
![series dan dataframe.PNG]()

#### pembuatan data frame
Data frame dapat dibuat menggunakan berbagai bentuk data, seperti:

*   Dictionary
*   Lists
*   Numpy ndarrays
*   Series

perintah utama untuk membuat data frame menggunakan pandas adalah dengan method `DataFrame()`

##### pembuatan data frame dari dictionary

In [ ]:
# definisikan data dictionary
dt_dictio = {
    'apples': [3, 2, 0, 1],
    'oranges' : [0, 3, 7, 2]
}

# buat dataframe dari dictionary
df = pd.DataFrame(dt_dictio)

#cetak dataframe
print(df)

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

##### pembuatan data frame dari list

In [32]:
#definisikan list
items = [['Phone','2000'], ['TV','1500'], ['Radio','800']]

# buat data frame dari list 
df = pd.DataFrame(items, columns=['item', 'price']) #columns digunakan untuk memberikan label pada kolom 

#cetak dataframe
print(df)

    item price
0  Phone  2000
1     TV  1500
2  Radio   800

##### pembuatan data frame dari numpy ndarray

In [ ]:
df2 = pd.DataFrame(
    np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
    columns=['column1', 'column2', 'column2'] )

print(df2)

   column1  column2  column2
0        1        2        3
1        4        5        6
2        7        8        9

##### pembuatan data frame dari series

In [ ]:
d = {
    'col1': [0, 1, 2, 3], 
    'col2': pd.Series([2, 3], index=[2, 3])
    }

df3 = pd.DataFrame(data=d, index=[0, 1, 2, 3])

print(df3)

   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

#### Load Data from file [.CSV]
download dataset **IRIS DATASET** yang akan diupload melalui link berikut [dataset](https://drive.google.com/file/d/1JYe7MfI2GOXxWef3MHhL2FqgKCJHVkAv/view?usp=sharing)
pastikan file telah berada pada directory yang sama dengan file ipynb
atau upload file CSV menggunakan perintah berikut

In [33]:
#upload file CSV
from google.colab import files
uploaded = files.upload()

Saving iris.csv to iris.csv

untuk load dataset [CSV] menggunakan pandas

In [34]:
df = pd.read_csv('iris.csv')
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

#### Load Data from file [.JSON]
download dataset **IRIS DATASET** yang akan diupload melalui link berikut [dataset](https://drive.google.com/file/d/1AhP35EZH1-MyE6-akj7qdEl9JxPbOvPt/view?usp=sharing)
pastikan file telah berada pada directory yang sama dengan file ipynb
atau upload file JSON menggunakan perintah berikut

In [35]:
#upload file JSON
from google.colab import files
uploaded = files.upload()

Saving iris.json to iris.json

untuk load dataset [JSON] menggunakan pandas

In [44]:
df_json = pd.read_json('iris.json')
df_json

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

#### Mengakses Data Frame

##### `DataFrame.head()` 
digunakan untuk mengakses sejumlah n data dimulai data paling awal

In [38]:
#untuk mengakses 5 data teratas dari data gunakan 

#load data iris
df = pd.read_csv('iris.csv')

#tampilkan 5 data teratas
df.head(5) #secara defult tanpa diberikan parameter yang dimunculkan adalah 5 data teratas

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

##### `DataFrame.tail()` 
digunakan untuk mengakses sejumlah n data dimulai data paling akhir

In [40]:
#tampilkan 5 data terbawah
df.tail(5) #secara defult tanpa diberikan parameter yang dimunculkan adalah 5 data terbawah

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

##### `DataFrame.sample(n=)` 
digunakan untuk mengakses sejumlah n data secara acak

In [ ]:
#tampilkan 5 data secara acak
df.sample(n=5) 

#untuk mengetahui perubahan hasilnya, perhatikan indexnya

     sepal.length  sepal.width  petal.length  petal.width     variety
11            4.8          3.4           1.6          0.2      Setosa
83            6.0          2.7           5.1          1.6  Versicolor
100           6.3          3.3           6.0          2.5   Virginica
104           6.5          3.0           5.8          2.2   Virginica
103           6.3          2.9           5.6          1.8   Virginica

#### function popular pada Data Frame

##### Rename Kolom Data Frame
gunakan perintah `DataFrame.rename(columns = '':'')`

In [ ]:
#load data iris
df = pd.read_csv('iris.csv')

#rename columns
df.rename(columns = {'sepal.length':'SepalLength',
                     'sepal.width':'SepalWidth',
                     'petal.length':'PetalLength',
                     'petal.width':'PetalWidth',
                     'variety':'class'
})

     SepalLength  SepalWidth  PetalLength  PetalWidth      class
0            5.1         3.5          1.4         0.2     Setosa
1            4.9         3.0          1.4         0.2     Setosa
2            4.7         3.2          1.3         0.2     Setosa
3            4.6         3.1          1.5         0.2     Setosa
4            5.0         3.6          1.4         0.2     Setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  Virginica
146          6.3         2.5          5.0         1.9  Virginica
147          6.5         3.0          5.2         2.0  Virginica
148          6.2         3.4          5.4         2.3  Virginica
149          5.9         3.0          5.1         1.8  Virginica

[150 rows x 5 columns]

##### `pandas.merge()`
Pandas `merge()` didefinisikan sebagai proses menyatukan dua kumpulan data menjadi satu dan menyelaraskan baris berdasarkan atribut atau kolom umum.

In [58]:
product = pd.DataFrame({
    'productID':['ptlite', 'prtmax', 'premmm', 'biosol', 'ptmax+'],
    'Desc' : ['Pertalite', 'Pertamax', 'Premium', 'Bio Solar', 'Pertamax Plus']
})

transaction = pd.DataFrame({
    'transactionID': [1, 2, 3, 4, 5, 6, 7, 8],
    'customer_name': ['Raka', 'Arra', 'Mina', 'Eko', 'Hyorin', 'Riski', 'Adam', 'Putri'],
    'productID':['prtmax', 'prtmax', 'premmm', 'ptlite' , 'ptmax+', 'ptlite', 'prtmax', 'ptlite'],
    'price': [12500, 25000, 20000, 35000, 12500, 22500, 25000, 20000]
})

df_report = pd.merge(transaction, product, how='outer', on='productID')
df_report

#ganti how='inner' dengan 'left', 'right', 'outer' kemudian amati hasilnya

   transactionID customer_name productID    price           Desc
0            1.0          Raka    prtmax  12500.0       Pertamax
1            2.0          Arra    prtmax  25000.0       Pertamax
2            7.0          Adam    prtmax  25000.0       Pertamax
3            3.0          Mina    premmm  20000.0        Premium
4            4.0           Eko    ptlite  35000.0      Pertalite
5            6.0         Riski    ptlite  22500.0      Pertalite
6            8.0         Putri    ptlite  20000.0      Pertalite
7            5.0        Hyorin    ptmax+  12500.0  Pertamax Plus
8            NaN           NaN    biosol      NaN      Bio Solar

In [52]:
transaction

   transactionID customer_name productID  price
0              1          Raka    prtmax  12500
1              2          Arra    prtmax  25000
2              3          Mina    premmm  20000
3              4           Eko    ptlite  35000
4              5        Hyorin    ptmax+  12500
5              6         Riski    ptlite  22500
6              7          Adam    prtmax  25000
7              8         Putri    ptlite  20000

In [53]:
product

  productID           Desc
0    ptlite      Pertalite
1    prtmax       Pertamax
2    premmm        Premium
3    biosol      Bio Solar
4    ptmax+  Pertamax Plus